//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServerConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Single_Msg
    {
        public int ID { get; set; }
        public string Single_Msg_ID { get; set; }
        public string Msg_Content { get; set; }
        public string Send_Time { get; set; }
        public string From_User_ID { get; set; }
        public string To_User_ID { get; set; }
        public string Msg_Type_ID { get; set; }
    
        public virtual C_Msg_Type C_Msg_Type { get; set; }
        public virtual C_User C_User { get; set; }
        public virtual C_User C_User1 { get; set; }
    }
}
