//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServerConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User_Status
    {
        public int ID { get; set; }
        public string User_ID { get; set; }
        public string Status_ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public string Status_Changed_Time { get; set; }
    
        public virtual C_Status C_Status { get; set; }
        public virtual C_User C_User { get; set; }
    }
}
