//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServerConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_User()
        {
            this.C_Group_Msg_Status = new HashSet<C_Group_Msg_Status>();
            this.C_Group_User = new HashSet<C_Group_User>();
            this.C_Multi_Msg = new HashSet<C_Multi_Msg>();
            this.C_Single_Msg = new HashSet<C_Single_Msg>();
            this.C_Single_Msg1 = new HashSet<C_Single_Msg>();
            this.C_User_Status = new HashSet<C_User_Status>();
        }
    
        public int ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public string City { get; set; }
        public string User_ID { get; set; }
        public string User_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Group_Msg_Status> C_Group_Msg_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Group_User> C_Group_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Multi_Msg> C_Multi_Msg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Single_Msg> C_Single_Msg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Single_Msg> C_Single_Msg1 { get; set; }
        public virtual C_User_Type C_User_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_User_Status> C_User_Status { get; set; }
    }
}
